#!/usr/bin/env bash
python3 ../scripts_py/move_img.py \
        --img_dir /media/yanjiezhang/ian/dataset/FE108_aedat4_to_nbinsGTP \
        --out_dir /media/yanjiezhang/ian/dataset/FE108 \
        --file_type png